# Generated by Django 3.1.4 on 2020-12-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Article',
            old_name='publication_date',
            new_name='publication_data',
        ),
    ]
