# Generated by Django 3.1.4 on 2020-12-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201229_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='publication_data',
            new_name='publication_date',
        ),
    ]
